### ISSUE TITLE
Symbol for Enemy and Neutral do not draw from player.py, but from Corporation.py

### ISSUE THREAD

**Issue by Julian-B** [baxter-oop/AndOre#108] opened 2016-08-02 19:41 UTC
Rewrite calculate_standing in corporation.py to reference values of _class_ Player in player.py

**Comment by JCharante** [comment] 2016-08-02 19:45
calculate_standing in corporation.py is perfectly fine, it's other parts that aren't using the player icons in player.py and instead are using what they get from calculate_standing. Issue closed as a duplicate of #107

**Closed by JCharante** 2016-08-02 19:45 UTC
